name: CI/CD Pipeline for Node.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Archive the application
    - name: Archive Application
      run: zip -r app.zip .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download artifact
    - name: Download Build
      uses: actions/download-artifact@v3
      with:
        name: app.zip

    # Step 2: Deploy to Server
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        scp -i C:\Users\Bhagyasri\Downloads\keypair1.pem app.zip ec2-user@18.168.254.230:/home/ec2-user/nodejs-app
        ssh -i C:\Users\Bhagyasri\Downloads\keypair1.pem ec2-user@18.168.254.230 << EOF
          cd /home/ec2-user/nodejs-app
          unzip -o app.zip
          npm install --production
          pm2 restart app || pm2 start index.js --name "nodejs-app"
        EOF
